PW_MACHINE_NAME="promptworks-shadowlab-main"
PW_BUILD_NR="promptworks-os-v1.0.0"
PW_FIRMWARE_REPO="git@github.com:Array-DB/Firmware-Works.git"
PW_BACKUP_SOURCE="/run/media/array/899d872f-9b62-49cc-9f3c-22eaabcd5170/@home/array"
PW_USERNAME="$(whoami)"
PW_USER_HOME="$HOME"
PW_PROJECTS_DIR="$HOME/Projects"
PW_WORKSPACE_DIR="$HOME/Workspace"
